version: '3.4'

services:
  vikusdocker:
    image: vikusdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    # command: gunicorn --bind 5000 --workers 1 --threads 8 --timeout 0 main:app
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  redis:
    image: "redis:alpine"
