version: '3.4'

services:
  vikusdocker-gpu:
    # image: vikusdocker
    build:
      context: .
      dockerfile: gpu.Dockerfile
    ports:
      - 5000:5000
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  redis:
    image: "redis:alpine"

  webserver:
    #image: nginx:alpine
    build: ./services/nginx
    ports:
      - 8000:8000
    volumes:
      - ./data:/usr/share/nginx/html/data
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
