version: '3.4'

services:
  vikusdocker:
    # image: vikusdocker
    build: ./services/vikusdocker
    ports:
      - 5000:5000
    # command: gunicorn --bind 5000 --workers 1 --threads 8 --timeout 0 main:app
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  redis:
    image: "redis:alpine"

  webserver:
    #image: nginx:alpine
    build: ./services/nginx
    ports:
      - 8000:8000
    volumes:
      - ./data:/usr/share/nginx/html/data
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
