version: '3.4'

services:
  vikusdocker:
    image: vikusdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    # command: gunicorn --bind 5000 --workers 1 --threads 8 --timeout 0 main:app
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      #- ./sharpsheet:/root/sharpsheet
      #- ./vikus-docker-frontend:/root/frontend

  redis:
    image: "redis:alpine"

  webserver:
    image: "nginx:alpine"
    ports:
      - 8000:80
    volumes:
      - ./data:/usr/share/nginx/html/data
      # - ./vikus-viewer:/usr/share/nginx/html/viewer
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - ./vikus-docker-frontend:/usr/share/nginx/html/frontend
